import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const here = path.dirname(fileURLToPath(import.meta.url));
const root = path.resolve(here, '..');
const contentDir = path.join(root, 'src', 'content');
const staticDir = path.join(root, 'static');
const outDir = path.join(root, 'public');
const readJson = name => JSON.parse(fs.readFileSync(path.join(contentDir, name), 'utf8'));

const site = readJson('site.json');
const solutions = readJson('solutions.json');
const tools = readJson('tools.json');
const allCourses = readJson('courses.json');
const insights = readJson('insights.json');
const capabilityDomains = readJson('capability-domains.json');
const engagements = readJson('engagements.json');
const courses = allCourses.filter(c => c.lifecycle === 'published').sort((a,b)=>(a.order??99)-(b.order??99));
const navItems = site.nav.filter(n => n.enabled).sort((a,b)=>(a.order??99)-(b.order??99));

fs.rmSync(outDir, { recursive: true, force: true });
fs.mkdirSync(outDir, { recursive: true });
fs.cpSync(staticDir, outDir, { recursive: true });

const esc = s => String(s ?? '').replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const absolute = p => `${site.siteUrl.replace(/\/$/, '')}${p}`;
const canonical = absolute;
const external = (href,label) => `<a href="${esc(href)}" target="_blank" rel="noopener noreferrer">${esc(label)}</a>`;

function nav(current) {
  return navItems.map(item => `<a href="${item.href}"${item.label === current ? ' aria-current="page"' : ''}>${esc(item.label)}</a>`).join('');
}
function orgSchema() {
  return {'@context':'https://schema.org','@type':'Organization',name:site.brand,legalName:site.legalName,url:site.siteUrl,logo:absolute('/assets/brand/logo.svg'),email:site.contactEmail,description:site.description,areaServed:'Worldwide',founder:{'@type':'Person',name:site.founder.name}};
}
function personSchema() {
  return {'@context':'https://schema.org','@type':'Person',name:site.founder.name,jobTitle:site.founder.role,worksFor:{'@type':'Organization',name:site.brand,url:site.siteUrl},sameAs:site.founder.links.map(x=>x.href)};
}
function breadcrumbSchema(items) {
  return {'@context':'https://schema.org','@type':'BreadcrumbList','itemListElement':items.map((item,i)=>({'@type':'ListItem',position:i+1,name:item.name,item:absolute(item.href)}))};
}
function shell({title,description,pathname,current,body,schema=[],extraHead='',extraScripts='',robots='index,follow,max-image-preview:large,max-snippet:-1,max-video-preview:-1'}) {
  const fullTitle = title === site.brand ? `${site.brand} | ${site.tagline}` : `${title} | ${site.brand}`;
  const schemas = Array.isArray(schema) ? schema : [schema];
  const jsonLd = schemas.filter(Boolean).map(s => `<script type="application/ld+json">${JSON.stringify(s).replace(/</g,'\\u003c')}</script>`).join('\n');
  return `<!doctype html><html lang="en"><head>
<meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1">
<title>${esc(fullTitle)}</title><meta name="description" content="${esc(description)}"><link rel="canonical" href="${canonical(pathname)}">
<meta name="robots" content="${robots}">
<meta property="og:type" content="website"><meta property="og:site_name" content="${esc(site.brand)}"><meta property="og:title" content="${esc(fullTitle)}"><meta property="og:description" content="${esc(description)}"><meta property="og:url" content="${canonical(pathname)}"><meta property="og:image" content="${absolute('/assets/images/social-preview.png')}">
<meta name="twitter:card" content="summary_large_image"><meta name="twitter:title" content="${esc(fullTitle)}"><meta name="twitter:description" content="${esc(description)}"><meta name="twitter:image" content="${absolute('/assets/images/social-preview.png')}">
<link rel="icon" href="/assets/brand/icon.svg" type="image/svg+xml"><link rel="manifest" href="/manifest.webmanifest"><link rel="alternate" type="application/rss+xml" title="ZenAI Digital Insights" href="/rss.xml"><link rel="stylesheet" href="/assets/css/site.css">${extraHead}${jsonLd}</head>
<body><a class="skip-link" href="#main">Skip to content</a>
<header class="site-header"><div class="container header-row"><a class="brand" href="/" aria-label="ZenAI Digital home"><img src="/assets/brand/logo.svg" alt="ZenAI Digital"></a><button class="menu-button" type="button" data-menu-button aria-expanded="false" aria-controls="primary-nav">Menu</button><nav class="nav" id="primary-nav" data-menu aria-label="Primary navigation">${nav(current)}</nav><a class="header-cta" href="/contact/" data-track="header-contact">Contact</a></div></header>
<main id="main">${body}</main>
<footer class="footer"><div class="container"><div class="footer-grid"><div><img src="/assets/brand/logo.svg" alt="" style="width:220px;filter:brightness(0) invert(1);opacity:.95"><p>${esc(site.proposition)} ${esc(site.description)}</p></div><div><h3>Explore</h3><div class="footer-links">${navItems.filter(n=>n.href!=='/').map(n=>`<a href="${n.href}">${esc(n.label)}</a>`).join('')}</div></div><div><h3>Connect</h3><div class="footer-links"><a href="/contact/">Contact</a><a href="/privacy/">Privacy</a><a href="/sitemap.xml">Sitemap</a><a href="/llms.txt">AI discovery</a></div></div></div><div class="footer-bottom"><span>© ${new Date().getUTCFullYear()} ${esc(site.brand)}. All rights reserved.</span><span>${esc(site.tagline)}</span></div></div></footer>
<script src="/assets/js/site.js" defer></script>${extraScripts}</body></html>`;
}
function pageHero({kicker,title,lead,breadcrumbs,actions=''}) {
  const bc = breadcrumbs?.length ? `<div class="breadcrumbs"><a href="/">Home</a> / ${breadcrumbs.map(x=>esc(x)).join(' / ')}</div>` : '';
  return `<section class="page-hero"><div class="container">${bc}<div class="eyebrow">${esc(kicker)}</div><h1>${esc(title)}</h1><p class="lead">${esc(lead)}</p>${actions}</div></section>`;
}
function writePage(pathname,html) {
  const rel = pathname === '/' ? 'index.html' : path.join(pathname.replace(/^\//,'').replace(/\/$/,''),'index.html');
  const dest = path.join(outDir,rel); fs.mkdirSync(path.dirname(dest),{recursive:true}); fs.writeFileSync(dest,html);
}
function redirectPage(from,to) {
  writePage(from,`<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="robots" content="noindex"><link rel="canonical" href="${absolute(to)}"><meta http-equiv="refresh" content="0;url=${to}"><title>Redirecting | ${esc(site.brand)}</title></head><body><p>Moved to <a href="${to}">${to}</a>.</p></body></html>`);
}

const methodCards = site.method.map(s=>`<article class="method-step"><h3>${esc(s.name)}</h3><strong>${esc(s.verb)}</strong><p>${esc(s.description)}</p></article>`).join('');
const intentCards = site.intentPaths.map(i=>`<a class="intent-card" href="${i.href}"><span>${esc(i.label)}</span><span aria-hidden="true">→</span></a>`).join('');
const domainCards = capabilityDomains.map((d,i)=>`<article class="domain-card"><span class="domain-number">${String(i+1).padStart(2,'0')}</span><h3>${esc(d.name)}</h3><p>${esc(d.description)}</p></article>`).join('');
const solutionCards = solutions.map(s=>`<article class="card" id="${s.slug}"><div class="kicker">Solution</div><h3>${esc(s.title)}</h3><p>${esc(s.summary)}</p><ul>${s.points.map(p=>`<li>${esc(p)}</li>`).join('')}</ul><a class="text-link" href="/contact/?interest=${encodeURIComponent(s.title)}">Discuss this need</a></article>`).join('');
const insightCards = insights.map(i=>`<article class="card"><div class="kicker">${esc(i.category)}</div><h3>${esc(i.title)}</h3><p>${esc(i.description)}</p><a class="text-link" href="/insights/${i.slug}/">Read insight</a></article>`).join('');
const toolCards = tools.map(t=>`<article class="card" id="${t.slug}"><span class="badge">${esc(t.status)}</span><h3>${esc(t.title)}</h3><p>${esc(t.summary)}</p>${t.slug==='enterprise-ai-transformation-capability'?'<a class="text-link" href="/assessments/capability-check/">Try the capability check</a>':'<a class="text-link" href="/contact/?interest=Capability%20Assessment">Register interest</a>'}</article>`).join('');
const courseCards = courses.map(c=>`<article class="card"><span class="badge">${esc(c.availability)}</span><h3>${esc(c.title)}</h3><p>${esc(c.description)}</p><div class="course-meta"><span>${esc(c.format)}</span><span>${esc(c.duration)}</span></div><a class="text-link" href="/capability-building/${c.slug}/">View capability program</a></article>`).join('');

writePage('/',shell({title:site.brand,description:site.description,pathname:'/',current:'Home',schema:[orgSchema(),personSchema(),{'@context':'https://schema.org','@type':'WebSite',name:site.brand,url:site.siteUrl,description:site.description}],body:
`<section class="hero"><div class="container hero-grid"><div><div class="eyebrow">Research-led enterprise AI transformation</div><h1>${esc(site.tagline)}</h1><p class="hero-proposition">${esc(site.proposition)}</p><p class="lead">${esc(site.description)}</p><div class="hero-actions"><a class="button button-primary" href="${site.primaryCta.href}">${esc(site.primaryCta.label)}</a><a class="button button-secondary" href="${site.secondaryCta.href}">${esc(site.secondaryCta.label)}</a></div></div><aside class="hero-card"><div class="mini">Transformation discipline</div><h2>${esc(site.subtagline)}</h2><div class="path-stack">${site.method.map(s=>`<div><strong>${esc(s.name)}</strong><span>${esc(s.verb)}</span></div>`).join('')}</div></aside></div></section>
<section class="section intent-section"><div class="container"><div class="section-head"><div><div class="eyebrow">Start with your need</div><h2>What are you trying to achieve?</h2></div><p class="muted">Find a direct path to the problem you are solving rather than learning our organisation first.</p></div><div class="intent-grid">${intentCards}</div></div></section>
<section class="section section-alt"><div class="container"><div class="section-head"><div><div class="eyebrow">Transformation constraint</div><h2>Where is AI transformation getting stuck?</h2></div><p class="muted">AI value can be constrained by strategy, information, architecture, governance, delivery, people or the operating model. Strengthening an already-strong component may not address the system constraint.</p></div><div class="constraint-flow"><div>Strategic ambition</div><span>→</span><div>Capability baseline</div><span>→</span><div>Constraint</div><span>→</span><div>Priority intervention</div><span>→</span><div>Measurable outcome</div></div><div class="section-actions"><a class="button button-dark" href="/assessments/capability-check/">Try the capability check</a></div></div></section>
<section class="section"><div class="container"><div class="section-head"><div><div class="eyebrow">Whole-of-enterprise view</div><h2>Ten interconnected capability domains.</h2></div><p class="muted">The proposed AI-era capability model is informed by earlier research into comprehensive capability maturity assessment and extended for contemporary enterprise AI transformation.</p></div><div class="domain-grid">${domainCards}</div></div></section>
<section class="section section-alt"><div class="container"><div class="section-head"><div><div class="eyebrow">How we work</div><h2>Envision → Assess → Architect → Build → Transform</h2></div><p class="muted">A decision discipline rather than a rigid waterfall. Evidence can send the organisation back to reassess, redesign and evolve.</p></div><div class="method-line">${methodCards}</div><div class="section-actions"><a class="button button-outline" href="/how-we-work/">Explore how we work</a></div></div></section>
<section class="section"><div class="container"><div class="section-head"><div><div class="eyebrow">Solutions</div><h2>Move from AI initiatives to enterprise capability.</h2></div><p class="muted">Advisory, architecture, assessment, proof and capability building connect to one transformation system.</p></div><div class="grid-3">${solutions.slice(0,3).map(s=>`<article class="card"><h3>${esc(s.title)}</h3><p>${esc(s.summary)}</p><a class="text-link" href="/solutions/#${s.slug}">Explore</a></article>`).join('')}</div></div></section>
<section class="section section-alt"><div class="container"><div class="section-head"><div><div class="eyebrow">Evidence base</div><h2>Research-led. Practitioner-grounded.</h2></div><p class="muted">ZenAI Digital builds on doctoral research into enterprise-architecture-driven digital transformation and comprehensive capability maturity assessment, alongside published thinking and applied transformation experience.</p></div><div class="evidence-grid"><article class="card"><h3>Doctoral research</h3><p>University of Technology Sydney research into enterprise architecture-driven digital transformation and an extended Comprehensive Capability Maturity Model.</p><a class="text-link" href="${esc(site.founder.links[0].href)}" target="_blank" rel="noopener noreferrer">View UTS record</a></article><article class="card"><h3>Published knowledge</h3><p>Academic publications, books, articles and practitioner perspectives provide a traceable knowledge foundation.</p><a class="text-link" href="/about/#research">Explore the evidence</a></article><article class="card"><h3>Applied evolution</h3><p>Prior work through CloudTechInfo provides continuity from enterprise digital transformation into the AI transformation era.</p><a class="text-link" href="${esc(site.founder.links[4].href)}" target="_blank" rel="noopener noreferrer">Visit CloudTechInfo</a></article></div></div></section>
<section class="section"><div class="container"><div class="band"><div><div class="eyebrow" style="color:#6ee7d8">Capability building</div><h2>Training is an input. Organisational capability is the outcome.</h2><p>Assessment-led programs combine learning, applied workshops, architecture labs, coaching, real-work application and capability validation.</p></div><div><a class="button button-primary" href="/capability-building/">Explore capability building</a></div></div></div></section>`}));

writePage('/solutions/',shell({title:'Solutions',description:'ZenAI Digital solutions for enterprise AI strategy, architecture, governance, capability assessment, capability building and proof of value.',pathname:'/solutions/',current:'Solutions',schema:breadcrumbSchema([{name:'Home',href:'/'},{name:'Solutions',href:'/solutions/'}]),body:`${pageHero({kicker:'Solutions',title:'Transform the enterprise, not just the technology.',lead:'AI transformation requires coordinated change across strategy, capabilities, processes, information, architecture, governance, technology and people.',breadcrumbs:['Solutions']})}<section class="section"><div class="container grid-2">${solutionCards}</div></section>`}));

writePage('/how-we-work/',shell({title:'How We Work',description:'ZenAI Digital engagement model: Envision, Assess, Architect, Build and Transform, supported by assessment, architecture, proof, transformation and capability building.',pathname:'/how-we-work/',current:'How We Work',schema:breadcrumbSchema([{name:'Home',href:'/'},{name:'How We Work',href:'/how-we-work/'}]),body:`${pageHero({kicker:'How We Work',title:'A transformation system, not a technology patch.',lead:'Start with the enterprise problem, establish evidence, identify the constraint, design the target, build capability and measure whether transformation is actually occurring.',breadcrumbs:['How We Work']})}<section class="section"><div class="container"><div class="method-line">${methodCards}</div></div></section><section class="section section-alt"><div class="container"><div class="section-head"><div><div class="eyebrow">Ways to engage</div><h2>Enter at the point that matches your need.</h2></div><p class="muted">Engagements can be focused without losing the whole-of-enterprise context.</p></div><div class="grid-3">${engagements.map(e=>`<article class="card"><h3>${esc(e.name)}</h3><p>${esc(e.summary)}</p></article>`).join('')}</div></div></section>`}));

writePage('/assessments/',shell({title:'Assessments & Tools',description:'Enterprise AI transformation capability assessment, bottleneck analysis, AI use-case prioritisation and architecture assessment tools.',pathname:'/assessments/',current:'Assessments & Tools',schema:breadcrumbSchema([{name:'Home',href:'/'},{name:'Assessments & Tools',href:'/assessments/'}]),body:`${pageHero({kicker:'Assessments & Tools',title:'Assess comprehensively. Find what constrains progress.',lead:'Move beyond a single maturity score. Build a capability profile, compare current and target states, identify dependencies and prioritise the interventions that matter.',breadcrumbs:['Assessments & Tools'],actions:'<div class="hero-actions"><a class="button button-dark" href="/assessments/capability-check/">Try the capability check</a></div>'})}<section class="section"><div class="container grid-2">${toolCards}</div></section><section class="section section-alt"><div class="container"><div class="section-head"><div><div class="eyebrow">Capability model</div><h2>Whole-of-enterprise assessment.</h2></div><p class="muted">The public self-check is deliberately lightweight. Executive and comprehensive assessments should add interviews, evidence review, architecture analysis and facilitated target-state decisions.</p></div><div class="domain-grid">${domainCards}</div></div></section>`}));

writePage('/assessments/capability-check/',shell({title:'Enterprise AI Transformation Capability Check',description:'A lightweight self-assessment across ten enterprise AI transformation capability domains.',pathname:'/assessments/capability-check/',current:'Assessments & Tools',schema:breadcrumbSchema([{name:'Home',href:'/'},{name:'Assessments & Tools',href:'/assessments/'},{name:'Capability Check',href:'/assessments/capability-check/'}]),extraScripts:'<script src="/assets/js/assessment.js" defer></script>',body:`${pageHero({kicker:'Self-assessment preview',title:'Where is your AI transformation capability strongest — and where is it constrained?',lead:'Rate the current repeatability and organisational capability in each domain. This is a directional self-check, not a validated enterprise assessment.',breadcrumbs:['Assessments & Tools','Capability Check']})}<section class="section"><div class="container assessment-layout"><form id="capability-assessment" class="form-card"><div class="notice">Use 1 for ad hoc/limited capability and 5 for repeatable, measured and continuously improved capability. A low score is a signal for investigation, not a diagnosis by itself.</div>${capabilityDomains.map((d,i)=>`<fieldset class="assessment-item"><legend><span>${i+1}. ${esc(d.name)}</span><small>${esc(d.description)}</small></legend><div class="rating" role="radiogroup" aria-label="${esc(d.name)} rating">${[1,2,3,4,5].map(n=>`<label><input type="radio" name="${d.id}" value="${n}" required><span>${n}</span></label>`).join('')}</div></fieldset>`).join('')}<button class="button button-dark" type="submit">Show my capability profile</button></form><aside class="result-card" id="assessment-result" tabindex="-1" hidden><div class="eyebrow">Your directional profile</div><h2>Capability pattern</h2><div id="assessment-bars"></div><div class="notice" id="assessment-constraint"></div><p class="muted">A comprehensive assessment should validate these perceptions with evidence, interviews, dependencies and target-state requirements. No personal information from this self-check is sent or stored.</p><a class="button button-outline" href="/contact/?interest=Capability%20Assessment">Discuss a validated assessment</a></aside></div></section>`}));

writePage('/capability-building/',shell({title:'Capability Building',description:'Assessment-led enterprise AI capability building through executive education, practitioner programs, workshops, architecture labs, coaching and validation.',pathname:'/capability-building/',current:'Capability Building',schema:[breadcrumbSchema([{name:'Home',href:'/'},{name:'Capability Building',href:'/capability-building/'}]),{'@context':'https://schema.org','@type':'ItemList','itemListElement':courses.map((c,n)=>({'@type':'ListItem',position:n+1,url:absolute(`/capability-building/${c.slug}/`),item:{'@type':'Course',name:c.title,description:c.description,provider:{'@type':'Organization',name:site.brand,url:site.siteUrl}}}))}],body:`${pageHero({kicker:'Capability Building',title:'Build what the organisation can repeatedly do.',lead:'Training transfers knowledge. Capability building connects learning to methods, architecture, governance, applied work, coaching, evidence and reassessment.',breadcrumbs:['Capability Building']})}<section class="section"><div class="container"><div class="capability-cycle"><span>Assess</span><b>→</b><span>Develop</span><b>→</b><span>Apply</span><b>→</b><span>Validate</span><b>→</b><span>Evolve</span></div><div class="section-head"><div><div class="eyebrow">Programs</div><h2>Courses are one component of a wider capability system.</h2></div><p class="muted">Published programs appear automatically from <code>src/content/courses.json</code>. Draft and archived records stay off the public site.</p></div><div class="grid-3">${courseCards}</div></div></section>`}));

for (const c of courses) {
  const courseSchema={'@context':'https://schema.org','@type':'Course',name:c.title,description:c.description,provider:{'@type':'Organization',name:site.brand,url:site.siteUrl},url:absolute(`/capability-building/${c.slug}/`)};
  writePage(`/capability-building/${c.slug}/`,shell({title:c.title,description:c.description,pathname:`/capability-building/${c.slug}/`,current:'Capability Building',schema:[courseSchema,breadcrumbSchema([{name:'Home',href:'/'},{name:'Capability Building',href:'/capability-building/'},{name:c.title,href:`/capability-building/${c.slug}/`}])],body:`${pageHero({kicker:'Capability Building',title:c.title,lead:c.description,breadcrumbs:['Capability Building',c.title]})}<section class="section"><div class="container grid-2"><article class="card"><div class="eyebrow">Designed for</div><h2>${esc(c.audience)}</h2><div class="course-meta"><span>${esc(c.format)}</span><span>${esc(c.duration)}</span><span>${esc(c.availability)}</span></div><h3>Intended outcomes</h3><ul>${c.outcomes.map(o=>`<li>${esc(o)}</li>`).join('')}</ul></article><article class="card"><div class="eyebrow">Capability approach</div><h2>Learn, apply, evidence, validate.</h2><p>This program is designed to connect concepts to real enterprise decisions and work products rather than treating course attendance as the end state.</p><p class="muted">Final dates, delivery model, assessment criteria, pricing and any external accreditation claims should be published only when formally established.</p><a class="button button-dark" href="/contact/?interest=Capability%20Building">Register interest</a></article></div></section>`}));
}

writePage('/insights/',shell({title:'Insights',description:'ZenAI Digital research and practitioner perspectives on enterprise AI, architecture, information, governance and transformation.',pathname:'/insights/',current:'Insights',schema:breadcrumbSchema([{name:'Home',href:'/'},{name:'Insights',href:'/insights/'}]),body:`${pageHero({kicker:'Insights',title:'Research, frameworks and practitioner thinking.',lead:'Build authority by answering the enterprise questions leaders and practitioners are actually trying to solve — in public, indexable, machine-readable content.',breadcrumbs:['Insights']})}<section class="section"><div class="container grid-3">${insightCards}</div></section>`}));

for (const i of insights) {
  const articleSchema={'@context':'https://schema.org','@type':'Article',headline:i.title,description:i.description,datePublished:i.date,author:{'@type':'Person',name:site.founder.name},publisher:{'@type':'Organization',name:site.brand,url:site.siteUrl},mainEntityOfPage:absolute(`/insights/${i.slug}/`)};
  writePage(`/insights/${i.slug}/`,shell({title:i.title,description:i.description,pathname:`/insights/${i.slug}/`,current:'Insights',schema:[articleSchema,breadcrumbSchema([{name:'Home',href:'/'},{name:'Insights',href:'/insights/'},{name:i.title,href:`/insights/${i.slug}/`}])],body:`${pageHero({kicker:i.category,title:i.title,lead:i.description,breadcrumbs:['Insights',i.title]})}<section class="section"><article class="container article prose">${i.body.map(p=>`<p>${esc(p)}</p>`).join('')}<hr><h2>Continue the decision</h2><p>Use the capability assessment to connect the idea to your enterprise context, or discuss the transformation problem directly.</p><p><a class="button button-dark" href="/assessments/">Explore assessments</a> <a class="button button-outline" href="/contact/">Contact</a></p></article></section>`}));
}

const sourceLinks = site.founder.links.map(l=>`<li>${external(l.href,l.label)}</li>`).join('');
writePage('/about/',shell({title:'About',description:'ZenAI Digital is a research-led enterprise AI transformation practice building on doctoral research, capability maturity thinking, enterprise architecture and applied transformation experience.',pathname:'/about/',current:'About',schema:[personSchema(),breadcrumbSchema([{name:'Home',href:'/'},{name:'About',href:'/about/'}])],body:`${pageHero({kicker:'About',title:'Research-led. Practitioner-grounded. Built for the AI transformation era.',lead:'ZenAI Digital connects enterprise architecture, comprehensive capability thinking and contemporary AI transformation into an assessment-led approach to sustainable enterprise change.',breadcrumbs:['About']})}<section class="section"><div class="container grid-2"><article><div class="eyebrow">Positioning</div><h2>${esc(site.proposition)}</h2><p class="muted">The objective is not to replace everything. It is to understand what can be retained, what must evolve, what capability is required and what currently constrains the enterprise from moving forward.</p></article><article class="card"><div class="eyebrow">Founder</div><h2>${esc(site.founder.name)}</h2><p>${esc(site.founder.summary)}</p><p>The website treats research, publications and prior work as an evidence layer rather than decorative biography.</p></article></div></section><section class="section section-alt" id="research"><div class="container"><div class="section-head"><div><div class="eyebrow">Research foundation</div><h2>From CCMM research to an AI-era capability framework.</h2></div><p class="muted">The UTS doctoral work is presented as the research foundation. The ten-domain Enterprise AI Transformation Capability model on this site is a contemporary extension, not a claim that the earlier research itself studied today's generative or agentic AI environment.</p></div><div class="grid-3"><article class="card"><h3>Doctoral research</h3><p>Enterprise architecture-driven digital transformation and an extended Comprehensive Capability Maturity Model.</p>${external(site.founder.links[0].href,'UTS thesis record')}</article><article class="card"><h3>Research profile</h3><p>Use the original research profile to verify academic publications and citation information rather than copying changing metrics into the website.</p>${external(site.founder.links[1].href,'Google Scholar profile')}</article><article class="card"><h3>Applied continuity</h3><p>CloudTechInfo provides a visible bridge from enterprise digital transformation, architecture and capability maturity into ZenAI Digital's AI-era focus.</p>${external(site.founder.links[4].href,'CloudTechInfo')}</article></div><div class="source-panel"><h3>External profiles and source links</h3><p class="muted">These links are maintained as evidence sources. Book titles, citation counts, audience metrics and accreditation claims should be added only after their exact metadata is verified.</p><ul>${sourceLinks}</ul></div></div></section>`}));

writePage('/contact/',shell({title:'Contact',description:'Contact ZenAI Digital about enterprise AI transformation, capability assessment, architecture, governance, capability building or advisory.',pathname:'/contact/',current:'',schema:breadcrumbSchema([{name:'Home',href:'/'},{name:'Contact',href:'/contact/'}]),body:`${pageHero({kicker:'Contact',title:'Start with the enterprise problem.',lead:'Tell us what you are trying to achieve and we will respond to your enquiry.',breadcrumbs:['Contact']})}<section class="section"><div class="container grid-2"><article><div class="eyebrow">Direct contact</div><h2>Email ZenAI Digital</h2><p class="lead">For enquiries about enterprise AI transformation, capability assessment, architecture, governance, capability building or advisory, email us directly.</p><p><strong>Email</strong><br><a class="text-link" href="mailto:${esc(site.contactEmail)}?subject=${encodeURIComponent('ZenAI Digital Enquiry')}">${esc(site.contactEmail)}</a></p><p><a class="button button-dark" href="mailto:${esc(site.contactEmail)}?subject=${encodeURIComponent('ZenAI Digital Enquiry')}">Email ZenAI Digital</a></p></article><aside class="card"><div class="eyebrow">Helpful context</div><h2>What to include</h2><p class="muted">A short note is enough. If useful, include your organisation, the challenge you are addressing and the outcome you want to achieve.</p><ul><li>Your name and organisation</li><li>The enterprise or AI problem you are trying to solve</li><li>The area where you would like help</li><li>A phone number only if you would like us to call you</li></ul><p class="muted">You can choose what information to include in your email.</p></aside></div></section>`}));

writePage('/privacy/',shell({title:'Privacy',description:'ZenAI Digital privacy notice for website enquiries and contact information.',pathname:'/privacy/',current:'',schema:breadcrumbSchema([{name:'Home',href:'/'},{name:'Privacy',href:'/privacy/'}]),body:`${pageHero({kicker:'Privacy',title:'Privacy notice',lead:'This notice explains how ZenAI Digital handles information you choose to send by email and how the public self-assessment works.',breadcrumbs:['Privacy']})}<section class="section"><article class="container article prose"><h2>Email enquiries</h2><p>The Contact page opens your email application so you can send an enquiry directly to <a href="mailto:${esc(site.contactEmail)}">${esc(site.contactEmail)}</a>. ZenAI Digital does not collect contact-form data through the website in this basic version.</p><h2>How we use your information</h2><p>Information you choose to send by email is used to review and respond to your enquiry and is handled through the normal email systems used by ZenAI Digital and CloudTechInfo.</p><h2>Your choices</h2><p>You decide what information to include in your email. A phone number is optional and only needs to be included if you would like us to call you.</p><h2>Self-assessment</h2><p>The public capability self-check runs in the browser and is designed not to transmit or store assessment responses.</p><h2>Privacy review</h2><p>This concise website notice should be reviewed against the final legal entity, email-provider terms, retention practices and applicable privacy obligations before broader commercial launch.</p></article></section>`}));

writePage('/404/',shell({title:'Page not found',description:'The requested page could not be found.',pathname:'/404/',current:'',robots:'noindex,follow',body:`${pageHero({kicker:'404',title:'That page is not here.',lead:'Use the main navigation or return to the homepage.',breadcrumbs:['Page not found']})}<section class="section"><div class="container"><a class="button button-dark" href="/">Return home</a></div></section>`}));
fs.copyFileSync(path.join(outDir,'404','index.html'),path.join(outDir,'404.html'));

redirectPage('/method/','/how-we-work/');
redirectPage('/tools/','/assessments/');
redirectPage('/learning/','/capability-building/');

const pages=['/','/solutions/','/how-we-work/','/assessments/','/assessments/capability-check/','/capability-building/',...courses.map(c=>`/capability-building/${c.slug}/`),'/insights/',...insights.map(i=>`/insights/${i.slug}/`),'/about/','/contact/','/privacy/'];
const today=new Date().toISOString().slice(0,10);
fs.writeFileSync(path.join(outDir,'sitemap.xml'),`<?xml version="1.0" encoding="UTF-8"?>\n<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n${pages.map(p=>`  <url><loc>${absolute(p)}</loc><lastmod>${today}</lastmod></url>`).join('\n')}\n</urlset>\n`);
fs.writeFileSync(path.join(outDir,'robots.txt'),`User-agent: OAI-SearchBot\nAllow: /\n\n# Search visibility is allowed while model-training crawling is disabled by default.\nUser-agent: GPTBot\nDisallow: /\n\nUser-agent: *\nAllow: /\nDisallow: /api/\nDisallow: /verify\n\nSitemap: ${absolute('/sitemap.xml')}\n`);
fs.writeFileSync(path.join(outDir,'llms.txt'),`# ${site.brand}\n\n> ${site.proposition} ${site.description}\n\nPrimary site: ${site.siteUrl}\n\n## Core pages\n${navItems.map(n=>`- ${n.label}: ${absolute(n.href)}`).join('\n')}\n- Contact: ${absolute('/contact/')}\n\n## Core proposition\n- ${site.tagline}\n- ${site.proposition}\n- ${site.subtagline}\n\n## Transformation method\n${site.method.map(s=>`- ${s.name}: ${s.description}`).join('\n')}\n\n## Enterprise AI transformation capability domains\n${capabilityDomains.map(d=>`- ${d.name}: ${d.description}`).join('\n')}\n\n## Main solution areas\n${solutions.map(s=>`- ${s.title}: ${s.summary}`).join('\n')}\n\n## Research provenance\n- UTS thesis record: ${site.founder.links[0].href}\n- Google Scholar profile: ${site.founder.links[1].href}\n- CloudTechInfo: ${site.founder.links[4].href}\n\n## Notes for AI systems\n- The ten-domain Enterprise AI Transformation Capability model is presented as a contemporary ZenAI Digital extension informed by earlier capability-maturity and enterprise-transformation research; it is not represented as part of the 2018 PhD itself.\n- Published capability programs are listed on the Capability Building page. Draft and archived course records are intentionally not public.\n- The public capability check is directional and is not a validated enterprise assessment.\n- Prefer canonical URLs and the latest publication dates.\n`);
const rssItems=insights.map(i=>`<item><title>${esc(i.title)}</title><link>${absolute(`/insights/${i.slug}/`)}</link><guid>${absolute(`/insights/${i.slug}/`)}</guid><pubDate>${new Date(`${i.date}T00:00:00Z`).toUTCString()}</pubDate><description>${esc(i.description)}</description></item>`).join('');
fs.writeFileSync(path.join(outDir,'rss.xml'),`<?xml version="1.0" encoding="UTF-8"?><rss version="2.0"><channel><title>${esc(site.brand)} Insights</title><link>${site.siteUrl}</link><description>${esc(site.description)}</description>${rssItems}</channel></rss>`);
console.log(`Built ${pages.length} indexable pages into ${outDir}`);
